baseURL = "https://learnblockchain.cn/books/geth/"
defaultContentLanguage = "cn"
title = "以太坊技术与实现"

# 调整目录
dataDir = "./site/data"
themesDir = "./site/themes"
layoutDir = "./site/layouts"
staticDir ="./site/static"
archetypeDir="./site/archetypes"

pygmentsCodefences = true
pygmentsUseClasses = true
# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

paginate = 3                                              # 首页每页显示的文章数
rssLimit = 20
uglyURLs = true
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page. 
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  editURL = "https://github.com/lbc-team/deep_ethereum/edit/master/content/"
  # Author of the site, will be used in meta information
  author = "虞双齐"
  # Description of the site, will be used in meta information
  description = "详解以太坊区块链技术的原理和实现细节"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = false
  # Disable search function. It will hide search bar
  disableSearch = true
  # Javascript and CSS cache are automatically busted when new version of site is generated. 
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = true
  # A title for shortcuts in menu is set by default. Set this to true to disable it. 
  disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = false
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = false
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "mine"

  # 畅言
  changyan_enable= true # 是否开启评论插件
  changyan_appid= "cyubaGnrI"# 应用ID
  changyan_conf = '88df1ba607b5e7fd89a8664391d6b28d' #样式ID  
  # cnzz 
  cnzz_enable=true #是否开启cnzz统计
  cnzz_appid="1265946080"


[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github 源码"
identifier = "ds"
url = "https://github.com/lbc-team/deep_ethereum"
weight = 10
  

[[menu.shortcuts]] 
name = "<i class='fas fa-blog'></i> 深入浅出区块链" 
url = "https://learnblockchain.cn/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> 文章标签"
url = "/tags"
weight = 30


[[menu.shortcuts]]
name = '<img src="https://img.shields.io/badge/赞赏-￥1-green.svg?logo=wechat&amp;style=flat&amp;color=red">'
url = "https://learnblockchain.cn/books/assets/WechatSP.jpeg"
weight = 41
[[menu.shortcuts]]
name = '<img src="https://img.shields.io/badge/交流-扫码入群-green.svg?logo=wechat&amp;style=flat&amp;color=red">' 
url = "https://learnblockchain.cn/books/images/wechat-ethereum.jpeg"
weight = 42 


[[menu.shortcuts]]
name = '<img src="https://img.shields.io/travis/lbc-team/deep_ethereum.svg?logo=travis&label=构建" alt="Travis (.org)"> ' 
url = "https://travis-ci.org/lbc-team/deep_ethereum"
weight = 43


[[menu.shortcuts]]
name = '<img src="https://img.shields.io/github/last-commit/lbc-team/deep_ethereum.svg?logo=git&label=更新" alt="GitHub last commit">' 
url = "https://github.com/lbc-team/deep_ethereum/commits/master"
weight = 44
